# Generated by Django 3.2 on 2024-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
