# Generated by Django 3.2 on 2024-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_actions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
